/**
 * Pulumi IaC Generator
 * Generates Pulumi TypeScript code for cloud infrastructure
 */

/**
 * Generate Pulumi TypeScript for AWS VPC
 * @param {Object} config - VPC configuration
 * @returns {string} - Pulumi TypeScript code
 */
export function generateAWSPulumi(config) {
  const { vpcCidr, vpcName = 'main', subnets = [] } = config;
  
  let code = `// ============================================
// AWS VPC and Subnet Configuration
// Generated by Subnet Zero
// ============================================

import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

// Configuration
const config = new pulumi.Config();
const environment = config.get("environment") || "production";

// ─────────────────────────────────────────
// VPC
// ─────────────────────────────────────────

const vpc = new aws.ec2.Vpc("${sanitizeName(vpcName)}", {
  cidrBlock: "${vpcCidr}",
  enableDnsHostnames: true,
  enableDnsSupport: true,
  tags: {
    Name: "${vpcName}",
    Environment: environment,
    GeneratedBy: "SubnetZero",
  },
});

// ─────────────────────────────────────────
// Internet Gateway
// ─────────────────────────────────────────

const igw = new aws.ec2.InternetGateway("${sanitizeName(vpcName)}-igw", {
  vpcId: vpc.id,
  tags: {
    Name: "${vpcName}-igw",
  },
});

// ─────────────────────────────────────────
// Subnets
// ─────────────────────────────────────────

`;

  subnets.forEach(subnet => {
    const varName = sanitizeName(subnet.name);
    const isPublic = subnet.tier === 'public';
    
    code += `const ${varName}Subnet = new aws.ec2.Subnet("${varName}", {
  vpcId: vpc.id,
  cidrBlock: "${subnet.cidr}",
  availabilityZone: "${subnet.az || 'us-east-1a'}",
  mapPublicIpOnLaunch: ${isPublic},
  tags: {
    Name: "${subnet.name}",
    Tier: "${subnet.tier || 'private'}",
    Environment: environment,
  },
});

`;
  });

  // Add route tables
  const publicSubnets = subnets.filter(s => s.tier === 'public');
  
  if (publicSubnets.length > 0) {
    code += `// ─────────────────────────────────────────
// Route Tables
// ─────────────────────────────────────────

const publicRouteTable = new aws.ec2.RouteTable("public-rt", {
  vpcId: vpc.id,
  routes: [
    {
      cidrBlock: "0.0.0.0/0",
      gatewayId: igw.id,
    },
  ],
  tags: {
    Name: "${vpcName}-public-rt",
  },
});

`;

    publicSubnets.forEach(subnet => {
      const varName = sanitizeName(subnet.name);
      code += `new aws.ec2.RouteTableAssociation("${varName}-rta", {
  subnetId: ${varName}Subnet.id,
  routeTableId: publicRouteTable.id,
});

`;
    });
  }

  // Add exports
  code += `// ─────────────────────────────────────────
// Exports
// ─────────────────────────────────────────

export const vpcId = vpc.id;
export const vpcCidr = vpc.cidrBlock;
`;

  subnets.forEach(subnet => {
    const varName = sanitizeName(subnet.name);
    code += `export const ${varName}SubnetId = ${varName}Subnet.id;
`;
  });

  return code;
}

/**
 * Generate Pulumi TypeScript for Azure VNet
 * @param {Object} config - VNet configuration
 * @returns {string} - Pulumi TypeScript code
 */
export function generateAzurePulumi(config) {
  const { 
    vpcCidr, 
    vpcName = 'main-vnet', 
    region = 'eastus',
    resourceGroup = 'rg-network',
    subnets = [] 
  } = config;
  
  let code = `// ============================================
// Azure VNet and Subnet Configuration
// Generated by Subnet Zero
// ============================================

import * as pulumi from "@pulumi/pulumi";
import * as azure from "@pulumi/azure-native";

// Configuration
const config = new pulumi.Config();
const environment = config.get("environment") || "production";

// ─────────────────────────────────────────
// Resource Group
// ─────────────────────────────────────────

const resourceGroup = new azure.resources.ResourceGroup("${sanitizeName(resourceGroup)}", {
  resourceGroupName: "${resourceGroup}",
  location: "${region}",
  tags: {
    Environment: environment,
    GeneratedBy: "SubnetZero",
  },
});

// ─────────────────────────────────────────
// Virtual Network
// ─────────────────────────────────────────

const vnet = new azure.network.VirtualNetwork("${sanitizeName(vpcName)}", {
  virtualNetworkName: "${vpcName}",
  resourceGroupName: resourceGroup.name,
  location: resourceGroup.location,
  addressSpace: {
    addressPrefixes: ["${vpcCidr}"],
  },
  tags: {
    Name: "${vpcName}",
    Environment: environment,
    GeneratedBy: "SubnetZero",
  },
});

// ─────────────────────────────────────────
// Subnets
// ─────────────────────────────────────────

`;

  subnets.forEach(subnet => {
    const varName = sanitizeName(subnet.name);
    
    code += `const ${varName}Subnet = new azure.network.Subnet("${varName}", {
  subnetName: "${subnet.name}",
  resourceGroupName: resourceGroup.name,
  virtualNetworkName: vnet.name,
  addressPrefix: "${subnet.cidr}",
});

`;
  });

  // Add exports
  code += `// ─────────────────────────────────────────
// Exports
// ─────────────────────────────────────────

export const vnetId = vnet.id;
export const vnetName = vnet.name;
export const resourceGroupName = resourceGroup.name;
`;

  subnets.forEach(subnet => {
    const varName = sanitizeName(subnet.name);
    code += `export const ${varName}SubnetId = ${varName}Subnet.id;
`;
  });

  return code;
}

/**
 * Generate Pulumi TypeScript for GCP VPC
 * @param {Object} config - VPC configuration
 * @returns {string} - Pulumi TypeScript code
 */
export function generateGCPPulumi(config) {
  const { 
    vpcName = 'main-vpc', 
    region = 'us-central1',
    subnets = [] 
  } = config;
  
  let code = `// ============================================
// GCP VPC and Subnet Configuration
// Generated by Subnet Zero
// ============================================

import * as pulumi from "@pulumi/pulumi";
import * as gcp from "@pulumi/gcp";

// Configuration
const config = new pulumi.Config();
const environment = config.get("environment") || "production";

// ─────────────────────────────────────────
// VPC Network
// ─────────────────────────────────────────

const network = new gcp.compute.Network("${sanitizeName(vpcName)}", {
  name: "${vpcName}",
  autoCreateSubnetworks: false,
  routingMode: "REGIONAL",
});

// ─────────────────────────────────────────
// Subnets
// ─────────────────────────────────────────

`;

  subnets.forEach(subnet => {
    const varName = sanitizeName(subnet.name);
    const subnetRegion = subnet.region || region;
    
    code += `const ${varName}Subnet = new gcp.compute.Subnetwork("${varName}", {
  name: "${subnet.name}",
  ipCidrRange: "${subnet.cidr}",
  region: "${subnetRegion}",
  network: network.id,
  privateIpGoogleAccess: ${subnet.tier !== 'public'},
});

`;
  });

  // Add firewall rules
  code += `// ─────────────────────────────────────────
// Firewall Rules
// ─────────────────────────────────────────

const allowInternal = new gcp.compute.Firewall("allow-internal", {
  name: "${vpcName}-allow-internal",
  network: network.name,
  allows: [
    { protocol: "icmp" },
    { protocol: "tcp", ports: ["0-65535"] },
    { protocol: "udp", ports: ["0-65535"] },
  ],
  sourceRanges: [${subnets.map(s => `"${s.cidr}"`).join(', ')}],
});

`;

  // Add exports
  code += `// ─────────────────────────────────────────
// Exports
// ─────────────────────────────────────────

export const networkId = network.id;
export const networkName = network.name;
export const networkSelfLink = network.selfLink;
`;

  subnets.forEach(subnet => {
    const varName = sanitizeName(subnet.name);
    code += `export const ${varName}SubnetId = ${varName}Subnet.id;
`;
  });

  return code;
}

/**
 * Generate Pulumi based on provider
 * @param {string} provider - Cloud provider (aws, azure, gcp)
 * @param {Object} config - Configuration object
 * @returns {string} - Pulumi TypeScript code
 */
export function generatePulumi(provider, config) {
  switch (provider) {
    case 'aws':
      return generateAWSPulumi(config);
    case 'azure':
      return generateAzurePulumi(config);
    case 'gcp':
      return generateGCPPulumi(config);
    default:
      return generateAWSPulumi(config);
  }
}

/**
 * Sanitize name for variable names
 * @param {string} name - Original name
 * @returns {string} - Sanitized camelCase name
 */
function sanitizeName(name) {
  const words = name.split(/[-_\s]+/);
  return words
    .map((word, index) => {
      if (index === 0) return word.toLowerCase();
      return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
    })
    .join('');
}

const pulumiExports = {
  generatePulumi,
  generateAWSPulumi,
  generateAzurePulumi,
  generateGCPPulumi
};

export default pulumiExports;

